version: 2.0

jobs:
  build:
      docker:
        - image: circleci/python:3.6
          environment:
            SQLALCHEMY_DATABASE_URI: postgresql://root@localhost:5432/circle-test_test
        - image: circleci/postgres:9.6.2-alpine
          environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle-test_test
      steps: &steps
        - checkout
        - run: sudo pip install -r requirements.txt
        - run: python --version ; pip --version ; pwd ; ls
        - run:
            name: Setup Code Climate test-reporter
            command: |
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
        - run:
            name: Run tests
            command: |
              ./cc-test-reporter before-build
              coverage run setup.py test
              coverage xml
              ./cc-test-reporter after-build -t coverage.py
