version: 2.0

jobs:
  build:
      docker:
        - image: circleci/python:3.6
          environment:
            SQLALCHEMY_DATABASE_URI: postgresql://root@localhost:5432/circle-test_test
        - image: circleci/postgres:9.6.2-alpine
          environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle-test_test
      steps: &steps
        - checkout
        - run: sudo pip install -r requirements.txt
        - run: sudo pip install flake8
        - run: python --version ; pip --version ; pwd ; ls
        # stop the build if there are Python syntax errors or undefined names
        - run: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
        # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
        - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#        - run: coverage run setup.py test
        - run:
            name: Setup Code Climate test-reporter
            command: |
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
        - run:
            name: Run tests
            command: |
              ./cc-test-reporter before-build
              coverage run setup.py test
              coverage xml
              ./cc-test-reporter after-build -t coverage.py
